"""empty message

Revision ID: 3c2f68a44376
Revises: 1901afac5b19
Create Date: 2024-06-10 13:54:39.407293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f68a44376'
down_revision = '1901afac5b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_table', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###
