"""empty message

Revision ID: 5424e5760493
Revises: 
Create Date: 2024-06-03 15:31:02.602028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5424e5760493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('username')
    )
    op.create_table('venues_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('burough', sa.String(), nullable=True),
    sa.Column('main_image', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('lgbtq_score', sa.Integer(), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users_table.id'], name=op.f('fk_venues_table_owner_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headliner', sa.String(), nullable=True),
    sa.Column('opening_acts', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_events_table_user_id_users_table')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues_table.id'], name=op.f('fk_events_table_venue_id_venues_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('review_content', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_reviews_table_user_id_users_table')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues_table.id'], name=op.f('fk_reviews_table_venue_id_venues_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.id'], name=op.f('fk_photos_table_event_id_events_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_photos_table_user_id_users_table')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues_table.id'], name=op.f('fk_photos_table_venue_id_venues_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_table')
    op.drop_table('reviews_table')
    op.drop_table('events_table')
    op.drop_table('venues_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
