"""empty message

Revision ID: 91ac482acb5a
Revises: 3c2f68a44376
Create Date: 2024-06-10 13:55:02.389890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ac482acb5a'
down_revision = '3c2f68a44376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
