"""empty message

Revision ID: ab4703a03686
Revises: e9b8e63168dc
Create Date: 2024-06-04 09:29:46.747420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4703a03686'
down_revision = 'e9b8e63168dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
