"""empty message

Revision ID: e9b8e63168dc
Revises: 5424e5760493
Create Date: 2024-06-04 09:17:56.252110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b8e63168dc'
down_revision = '5424e5760493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.drop_column('main_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
